#include <iostream> // LIBRERIA ESTANDAR DE C++ PARA PROCESADOR DE TEXTO.

using namespace std; //ESTA FUNCION NOS PERMITE EVITAR PONER STD EN CADA LINEA DE COGIDO, YA QUE ESTO ABARCA TODO.
int main () //PROGRAMA PRINCIPAL.
{
	
	cout<<"HOLA MUNDO"; // ESTA LINEA DE CODIGO NOS MUESTRA LA FRASE YA ESCRITA.
	                    //LA FUNCION cout SOlO MUESTRA TEXTO EN PANTALLA.
	
	
	return 0; // FINALIZACION DE PROGRAMA.
}//FINAL DEL PROGRAMA